### ISSUE TITLE
warp

### ISSUE THREAD

**Issue by lishufeier** [mdw771/tensorflow_interpolation_3d#1]
Sorry to bother you，but I'd like to ask you a question.What does the parameter “warp” represent？

**Comment by mdw771** [comment]
`warp` is a list of 3D coordinates to interpolate and should be given as a 2D tensor with shape (n_points, 3). I've added docstrings to the code in a new commit.

**Comment by lishufeier** [comment]
thanks for reply.Can you just give an example in code？

**Comment by lishufeier** [comment]
Cause I want to make a 16 * 16 * 16 3D data into a super-resolution 32 * 32 * 32,I set warp to[[0,0,0], [0,0,1], .......[31,31,31] ],but it ran incorrectly.

**Comment by lishufeier** [comment]
Thank you for reply.If I want to interpolate a 16 * 16 * 16 3D data into 32 * 32 * 32 cube data, which is equivalent to super-resolution processing, parameter "data" here should be my 16 * 16 * 16 sample data, parameter "warp" should be the list of three-dimensional coordinates to be interpolated [[0,0,0], [0,1],..., [31,31]], is that right?Looking foward to your reply.

**Comment by lishufeier** [comment]
Thank you for reply.If I want to interpolate a 16 * 16 * 16 3D data into 32 * 32 * 32 cube data, which is equivalent to super-resolution processing, parameter "data" here should be my 16 * 16 * 16 sample data, parameter "warp" should be the list of three-dimensional coordinates to be interpolated,i.e. [[0,0,0], [0,0,1],..., [31,31,31]], is that right?Looking foward to your reply.

**Comment by mdw771** [comment]
That’s right. If your output appears as a mirror reflection or inversion of what you expect, try swapping the axes of your warp tensor. You can always debug with a minimal (say 2x2x2) test input.

**Comment by lishufeier** [comment]
Actually, it's been going wrong at line“c000 = tf.gather_nd(data, i000)”and I can’t find the reason.I don't use tensorflow much, and I really don't understand many functions well.Can you guess the cause of the mistake？

**Comment by lishufeier** [comment]
I am eager for you to give an example of 3D interpolation, for example, interpolation of 2 * 2 * 2 data to 4 * 4 * 4.

**Comment by lishufeier** [comment]
Here is the test code that I interpolated 1 * 1 * 1 to 2 * 2 * 2, but the error was reported. Do you know the cause of the error？
    x=tf.constant([[[1]]])
    coor=[[0.0,0.0,0.0],[0.0,0.0,1.0],[0.0,1.0,0.0],[0.0,1.0,1.0],[1.0,0.0,0.0],[1.0,0.0,1.0],[1.0,1.0,0.0],[1.0,1.0,1.0]]
    y=biliniear_interpolation_3d(x,tf.convert_to_tensor(arr))
    sess=tf.Session()
    sess.run(y)

**Comment by mdw771** [comment]
Ok so the error is caused by giving indices beyond the size of `data` in `tf.gather_nd`. This function was originally not intended for interpolating at the upper boundary of the input tensor (e.g., at [1.5, 1.5, 2] for an input of shape [3, 3, 3]), nor for extrapolating out of the tensor. I've added a few lines to pad `data` around in the new commit so that you can interpolate at the boundary, but note that you still can't use it to extrapolate out of the object. For example, trying to get the value at [4, 4, 4] for an input with shape [2, 2, 2] is not allowed. 
A demonstrative script is as following:
```
xx, yy, zz = np.meshgrid(*([np.arange(2)] * 3))
a = yy * 4 + xx * 2 + zz
a = a.astype('float32')
print(a)
a = tf.constant(a)
coords = tf.constant([[0, 0.5, 0.5],
                      [0.5, 0.5, 0.5],
                      [0.7, 0.7, 0.7],
                      [0.7, 0.7, 0.9],
                      [1, 0.5, 0.5]], dtype=tf.float32)
sess = tf.Session()
sess.run(tf.global_variables_initializer())
b = sess.run(biliniear_interpolation_3d(a, coords))
print(b)
```
Also a few comments/suggestions:
1. When posting an issue at Github, please provide both your script and the error messages you got. This allows people to locate the issue faster. 
2. When getting an error, please read the error messages, and try to debug yourself before asking for an example script. If it is associated with a function coming from a well-documented external library like Tensorflow, check the documentation for that function if necessary. Most error messages are self-suggestive - like `tf.gather_nd` in this case. You could figure out that the error was caused by overflowing indices within a minute. That is often the fastest way to get yourself help especially for a short script like this.

**Comment by lishufeier** [comment]
I've got it.Thank you very much for your advice.

At 2019-11-23 00:45:29, "Triethanolamine" <notifications@github.com> wrote:


Ok so the error is caused by giving indices beyond the size of data in tf.gather_nd. This function was originally not intended for interpolating at the upper boundary of the input tensor (e.g., at [1.5, 1.5, 2] for an input of shape [3, 3, 3]), nor for extrapolating out of the tensor. I've added a few lines to pad data around in the new commit so that you can interpolate at the boundary, but note that you still can't use it to extrapolate out of the object. For example, trying to get the value at [4, 4, 4] for an input with shape [2, 2, 2] is not allowed.
A demonstrative script is as following:

xx, yy, zz = np.meshgrid(*([np.arange(2)] * 3))
a = yy * 4 + xx * 2 + zz
a = a.astype('float32')
print(a)
a = tf.constant(a)
coords = tf.constant([[0, 0.5, 0.5],
                      [0.5, 0.5, 0.5],
                      [0.7, 0.7, 0.7],
                      [0.7, 0.7, 0.9],
                      [1, 0.5, 0.5]], dtype=tf.float32)
sess = tf.Session()
sess.run(tf.global_variables_initializer())
b = sess.run(biliniear_interpolation_3d(a, coords))
print(b)


Also a few comments/suggestions:

When posting an issue at Github, please provide both your script and the error messages you got. This allows people to locate the issue faster.
When getting an error, please read the error messages, and try to debug yourself before asking for an example script. If it is associated with a function coming from a well-documented external library like Tensorflow, check the documentation for that function if necessary. Most error messages are self-suggestive - like tf.gather_nd in this case. You could figure out that the error was caused by overflowing indices within a minute. That is often the fastest way to get yourself help especially for a short script like this.
